msrv = "1.85"
cognitive-complexity-threshold = 25
too-many-lines-threshold = 100
allowed-idents-below-min-chars = ["x", "y", "i", "j", "k", "n", "fd", "tx", "rx", "id"]
type-complexity-threshold = 250
too-many-arguments-threshold = 7
missing-docs-in-crate-items = false
